### ISSUE TITLE
Feature request: add support for tv shows

### ISSUE THREAD

**Issue by agent255** [kaboussi/stream-cli#12]
It would be really cool to have support for tv shows.

**Comment by redelka00** [comment]
I'll add it later
but you need to configure your video player to remember the last position

**Comment by Aymane11** [comment]
> I'll add it later but you need to configure your video player to remember the last position

VLC by default suggests if you want to continue from the last position or start from the beginning

**Comment by redelka00** [comment]
> > I'll add it later but you need to configure your video player to remember the last position
> 
> VLC by default suggests if you want to continue from the last position or start from the beginning

Also mpv support it by adding this line to the config file `mpv --save-position-on-quit`

**Comment by Ozzy4201** [comment]
> I'll add it later but you need to configure your video player to remember the last position

Any update on this?

**Comment by kaboussi** [comment]
Done!
You can now type `python3 main.py serie`
