### ISSUE TITLE
"webtorrent is exiting..."

### ISSUE THREAD

**Issue by sw33zy** [kaboussi/stream-cli#24]
Running on wsl everything seems to work fine, I set up vlc, but a few seconds after choosing a movie it shows me the message "webtorrent is exiting...". I can't seem to stream any movie.... Every requirement is satisfied and vlc is installed. I'm using Xming to get acess to the graphical interface on windows.

**Comment by redelka00** [comment]
executing applications from the terminal on windows is different from UNIX
for UNIX systems to execute VLC you just need to type `vlc` in the terminal
for windows, I think you should pass the full path like `C:\path\to\file.exe`
Does someone confirm this?

**Comment by Aymane11** [comment]
> executing applications from the terminal on windows is different from UNIX for UNIX systems to execute VLC you just need to type `vlc` in the terminal for windows, I think you should pass the full path like `C:\path\to\file.exe` Does someone confirm this?

If VLC is in PATH, i think that it can be called only using the `vlc` command (there's even a part about [CLI VLC](https://wiki.videolan.org/VLC_command-line_help/) in their documentation)

**Comment by redelka00** [comment]
> > executing applications from the terminal on windows is different from UNIX for UNIX systems to execute VLC you just need to type `vlc` in the terminal for windows, I think you should pass the full path like `C:\path\to\file.exe` Does someone confirm this?
> 
> If VLC is in PATH, i think that it can be called only using the `vlc` command (there's even a part about [CLI VLC](https://wiki.videolan.org/VLC_command-line_help/) in their documentation)

So it should be called by the run process like Unix systems?  
    `subprocess.run(["webtorrent", magnet, vlc], check=True, shell=True)`

**Comment by kaboussi** [comment]
It should work after the latest update
and please make sure that you have VLC in your environment variable PATH.
